import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// 스터디 문서는 전부 draft: true → 프로덕션 빌드에서 제외됩니다.
// 프로덕션에서는 문서가 없으므로 아래 하드코딩 ID(intro, routine, *,/overview)를
// 그대로 두면 "sidebar document ids do not exist" 에러가 납니다.
// 따라서 프로덕션에서는 빈 사이드바를 반환합니다. (로컬 dev에서만 전체 노출)
const isDev = process.env.NODE_ENV !== "production";

const sidebars: SidebarsConfig = {
  studySidebar: isDev
    ? [
        "intro",
        "routine",
        {
          type: "category",
          label: "코딩 테스트",
          link: {
            type: "doc",
            id: "leetcode/overview",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "leetcode/weekly",
            },
          ],
        },
        {
          type: "category",
          label: "영어",
          link: {
            type: "doc",
            id: "english/overview",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "english/weekly",
            },
          ],
        },
        {
          type: "category",
          label: "글쓰기",
          link: {
            type: "doc",
            id: "writing/overview",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "writing/weekly",
            },
          ],
        },
      ]
    : [],
};

export default sidebars;
